const LOGIN = '/auth/login',
  REGISTER = '/auth/register',
  PROFILE = '/user/info',
  BALANCE = '/user/balance',
  LOGOUT = '/auth/logout',
  DEPOSIT = '/trade/recharge',
  DRAW = '/trade/withdraw',
  BIND_CARD = '/trade/card/bind',
  VERIFY_CARD = '/trade/card/verify',
  ADD_CARD = '/trade/card/new',
  LOCK_CARD = '/trade/card/lock',
  SET_LINK_REBATE = '/user/point/set/link',
  SET_SUB_REBATE = 'user/point/set',
  CREATE_SUB = '/user/sub/create',
  CHANGE_PSW = '/auth/password/reset',
  CHANGE_TRANS_PSW = '/auth/password/trade/reset',
  SET_TRANS_PSW = '/auth/password/trade/set',
  VERIFY_TRANS_PSW = '/auth/password/trade/check',
  GET_QUESTION_LIST = '/auth/question/list/all',
  GET_USER_QUESTION_LIST = '/auth/question/list/user',
  SET_USER_QUESTION_LIST = '/auth/question/set',
  VERIFY_QUESTION = '/auth/question/verify',
  NOTICE_LIST = '/message/main/list',
  NOTICE_DETAIL = '/message/main/detail',
  SET_NOTICE_READ = '/message/main/read',
  MESSAGE_LIST = '/message/personal/list',
  MESSAGE_DETAIL = '/message/personal/detail',
  SET_MESSAGE_READ = '/message/personal/read',
  DELETE_MESSAGE = '/message/personal/delete',
  TEAM_INFO = '/user/team',
  BET = '/lottery/bet',
  BET_HISTORY = '/user/bet_histroy';

export {
  LOGIN,
  REGISTER,
  PROFILE,
  BALANCE,
  LOGOUT,
  DEPOSIT,
  DRAW,
  BIND_CARD,
  VERIFY_CARD,
  ADD_CARD,
  LOCK_CARD,
  SET_LINK_REBATE,
  SET_SUB_REBATE,
  CREATE_SUB,
  CHANGE_PSW,
  CHANGE_TRANS_PSW,
  SET_TRANS_PSW,
  VERIFY_TRANS_PSW,
  GET_QUESTION_LIST,
  GET_USER_QUESTION_LIST,
  SET_USER_QUESTION_LIST,
  VERIFY_QUESTION,
  NOTICE_LIST,
  NOTICE_DETAIL,
  SET_NOTICE_READ,
  MESSAGE_LIST,
  MESSAGE_DETAIL,
  SET_MESSAGE_READ,
  DELETE_MESSAGE,
  TEAM_INFO,
  BET,
  BET_HISTORY
}
