export default [
  {
    categoryName: "经典时时彩",
    className: "",
    lotterys: [{
      lotteryId: 1,
      name: "重庆时时彩",
      flaglot: "cqssc",
      type: "hot",
      uri: "#/lottery/ssc/cqssc/cg",
    }, {
      lotteryId: 13,
      name: "天津时时彩",
      flaglot: "tjssc",
      type: "",
      uri: "#/lottery/ssc/tjssc/cg",
    }, {
      lotteryId: 6,
      name: "新疆时时彩",
      flaglot: "xjssc",
      type: "",
      uri: "#/lottery/ssc/xjssc/cg",
    }]
  },

  {
    categoryName: "高频时时彩",
    className: "category-ffc",
    lotterys: [{
      lotteryId: 28,
      name: "腾讯分分彩",
      flaglot: "txffc",
      type: "hot",
      uri: "#/lottery/ssc/txffc/cg",
      order: 1,
    }, {
      lotteryId: 29,
      name: "加拿大30秒",
      flaglot: "jnd30m",
      type: "hot",
      uri: "#/lottery/ssc/jnd30m/cg",
      order: 2,
    }, {
      lotteryId: 41,
      name: "多彩重庆30秒",
      flaglot: "cq30s",
      type: "new",
      uri: "#/lottery/ssc/cq30s/cg",
    }, {
      lotteryId: 42,
      name: "多彩腾讯30秒",
      flaglot: "tx30s",
      type: "new",
      uri: "#/lottery/ssc/tx30s/cg",
    }, {
      lotteryId: 19,
      name: "河内一分彩",
      flaglot: "hn1fc",
      type: "hot",
      uri: "#/lottery/ssc/hn1fc/cg",
      order: 5,
    }, {
      lotteryId: 14,
      name: "河内五分彩",
      flaglot: "hn5fc",
      type: "hot",
      uri: "#/lottery/ssc/hn5fc/cg",
      order: 6,
    }, {
      lotteryId: 26,
      name: "瑞典1分彩",
      flaglot: "rd1fc",
      type: "new",
      uri: "#/lottery/ssc/rd1fc/cg",
      order: 7,
    }, {
      lotteryId: 27,
      name: "瑞典2分彩",
      flaglot: "rd2fc",
      type: "new",
      uri: "#/lottery/ssc/rd2fc/cg",
      order: 8,
    }, {
      lotteryId: 38,
      name: "日本分分彩",
      flaglot: "rbffc",
      type: "",
      uri: "#/lottery/ssc/rbffc/cg",
    }, {
      lotteryId: 40,
      name: "印尼分分彩",
      flaglot: "ynffc",
      type: "",
      uri: "#/lottery/ssc/ynffc/cg",
    }, {
      lotteryId: 39,
      name: "西贡分分彩",
      flaglot: "xgffc",
      type: "",
      uri: "#/lottery/ssc/xgffc/cg",
    }, {
      lotteryId: 23,
      name: "杏耀秒秒彩",
      flaglot: "mmc",
      type: "",
      uri: "#/lottery/ssc/mmc/cg",
    }]
  },
  {
    categoryName: "11选5",
    className: "",
    lotterys: [{
      lotteryId: 35,
      name: "加拿大11选5",
      flaglot: "jnd11x5",
      type: "hot",
      uri: "#/lottery/ssc/jnd11x5/cg"
    }, {
      lotteryId: 8,
      name: "广东11选5",
      flaglot: "gd11x5",
      type: "",
      uri: "#/lottery/ssc/gd11x5/cg"
    }, {
      lotteryId: 7,
      name: "江西11选5",
      flaglot: "jx11x5",
      type: "",
      uri: "#/lottery/ssc/jx11x5/cg"
    }, {
      lotteryId: 5,
      name: "山东11选5",
      flaglot: "sd11x5",
      type: "",
      uri: "#/lottery/ssc/sd11x5/cg"
    }, {
      lotteryId: 30,
      name: "上海11选5",
      flaglot: "sh11x5",
      type: "",
      uri: "#/lottery/ssc/sh11x5/cg"
    }, {
      lotteryId: 31,
      name: "安徽11选5",
      flaglot: "ah11x5",
      type: "",
      uri: "#/lottery/ssc/ah11x5/cg"
    }]
  },
  {
    categoryName: "PK10/赛马",
    className: "",
    lotterys: [{
      lotteryId: 24,
      name: "北京PK拾",
      flaglot: "pk10",
      type: "hot",
      uri: "#/lottery/animate/pk10/1",
      order: 3
    }, {
      lotteryId: 34,
      name: "意大利PK拾",
      flaglot: "ydl10",
      type: "",
      uri: "#/lottery/animate/ydl10/1",
      order: 3
    }, {
      lotteryId: 25,
      name: "急速赛马",
      flaglot: "jssm",
      type: "hot",
      uri: "#/lottery/animate/jssm/1",
      order: 4
    }]
  },
  {
    categoryName: "3D/P3",
    className: "",
    lotterys: [{
      lotteryId: 37,
      name: "加拿大3D",
      flaglot: "3djnd",
      type: "hot",
      uri: "#/lottery/ssc/3djnd/cg",
      order: 2
    }, {
      lotteryId: 11,
      name: "3D福彩",
      flaglot: "3dfc",
      type: "",
      uri: "#/lottery/ssc/3dfc/cg"
    }, {
      lotteryId: 12,
      name: "排列3",
      flaglot: "pl3",
      type: "",
      uri: "#/lottery/ssc/pl3/cg"
    }]
  },
  {
    categoryName: "其他",
    className: "",
    lotterys: [{
      lotteryId: 20,
      name: "香港六合彩",
      flaglot: "xglhc",
      type: "",
      uri: "#/lottery/lhc/xglhc/1"
    }, {
      lotteryId: 15,
      name: "江苏快三",
      flaglot: "jsk3",
      type: "",
      uri: "#/lottery/ssc/jsk3/cg"
    }, {
      lotteryId: 9,
      name: "北京快乐8",
      flaglot: "bjkl8",
      type: "",
      uri: "#/lottery/ssc/bjkl8/cg"
    }]
  }]